import { MetadataRoute } from "next";
import { fetchBranches, fetchDoctors, fetchBlogs, fetchNews, fetchEvents, fetchSpecialities } from "@/lib/api";
import fs from "fs";
import path from "path";

const BASE = process.env.NEXT_PUBLIC_SITE_URL || "https://www.popularhospital.in";

/**
 * Recursively find all static routes in a directory that contain a page.tsx
 */
function getStaticRoutes(dirPath: string, basePath: string): string[] {
  let routes: string[] = [];
  try {
    if (!fs.existsSync(dirPath)) return routes;
    
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
    let hasPage = false;
    
    for (const entry of entries) {
      if (entry.isDirectory()) {
        // Skip dynamic routes, private folders, and specific exclusions
        if (
          entry.name.startsWith("[") || 
          entry.name.startsWith("_") ||
          entry.name === "dept"
        ) {
          continue;
        }
        const subPath = path.join(dirPath, entry.name);
        const subRoutes = getStaticRoutes(subPath, `${basePath}/${entry.name}`);
        routes = routes.concat(subRoutes);
      } else if (entry.name === "page.tsx" || entry.name === "page.js") {
        hasPage = true;
      }
    }
    
    // Add the current base path if it has a page.tsx
    if (hasPage && basePath !== "") {
      routes.push(basePath);
    }
  } catch (e) {
    console.error(`Error reading directory ${dirPath}`, e);
  }
  return routes;
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const [branches, doctors, blogs, news, events, specialities] = await Promise.all([
    fetchBranches().catch(() => []),
    fetchDoctors().catch(() => []),
    fetchBlogs().catch(() => []),
    fetchNews().catch(() => []),
    fetchEvents().catch(() => []),
    fetchSpecialities().catch(() => []),
  ]);

  const staticCorePages: MetadataRoute.Sitemap = [
    { url: BASE, lastModified: new Date(), changeFrequency: "daily", priority: 1 },
    { url: `${BASE}/doctors`, lastModified: new Date(), changeFrequency: "daily", priority: 0.9 },
    { url: `${BASE}/book`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE}/branches`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE}/opd`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE}/online-payment`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/stories`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
  ];

  // Auto-discover static routes from Next.js app directory structure
  const appDir = path.join(process.cwd(), "src", "app");
  
  const aboutPaths = getStaticRoutes(path.join(appDir, "about"), "/about");
  const departmentPaths = getStaticRoutes(path.join(appDir, "departments"), "/departments");
  const servicePaths = getStaticRoutes(path.join(appDir, "services"), "/services");
  const mediaPaths = getStaticRoutes(path.join(appDir, "media"), "/media");
  const careersPaths = getStaticRoutes(path.join(appDir, "careers"), "/careers");
  const blogStaticPaths = getStaticRoutes(path.join(appDir, "blog"), "/blog");
  const locationsPaths = getStaticRoutes(path.join(appDir, "locations"), "/locations");

  const autoGeneratedPages: MetadataRoute.Sitemap = [
    ...aboutPaths,
    ...departmentPaths,
    ...servicePaths,
    ...mediaPaths,
    ...careersPaths,
    ...blogStaticPaths,
    ...locationsPaths
  ].filter(p => !p.includes('/admin-login')).map((routePath) => ({
    url: `${BASE}${routePath}`,
    lastModified: new Date(),
    changeFrequency: routePath.includes('/departments') ? "monthly" : "weekly",
    priority: routePath.includes('/departments') ? 0.9 : 0.8,
  }));

  // Dynamic API routes
  const branchPages: MetadataRoute.Sitemap = branches.map((b: any) => ({
    url: `${BASE}/branches/${b.slug}`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: 0.7,
  }));

  const doctorPages: MetadataRoute.Sitemap = doctors.map((d: any) => ({
    url: `${BASE}/doctors/${d.slug}`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: 0.7,
  }));

  const blogPages: MetadataRoute.Sitemap = blogs.map((b: any) => ({
    url: `${BASE}/blog/${b.slug}`,
    lastModified: b.updatedAt ? new Date(b.updatedAt) : new Date(),
    changeFrequency: "weekly",
    priority: 0.6,
  }));

  const newsPages: MetadataRoute.Sitemap = news.map((n: any) => ({
    url: `${BASE}/media/news/${n.slug}`,
    lastModified: n.date ? new Date(n.date) : new Date(),
    changeFrequency: "monthly",
    priority: 0.6,
  }));

  const eventPages: MetadataRoute.Sitemap = events.map((e: any) => ({
    url: `${BASE}/media/events/${e.slug}`,
    lastModified: e.date ? new Date(e.date) : new Date(),
    changeFrequency: "monthly",
    priority: 0.6,
  }));

  const dynamicDepartmentPages: MetadataRoute.Sitemap = specialities
    .filter((s: any) => !departmentPaths.includes(`/departments/${s.slug}`))
    .map((s: any) => ({
      url: `${BASE}/departments/${s.slug}`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.9,
    }));

  return [
    ...staticCorePages, 
    ...autoGeneratedPages, 
    ...branchPages, 
    ...doctorPages,
    ...blogPages,
    ...newsPages,
    ...eventPages,
    ...dynamicDepartmentPages
  ];
}
