export const blogPostsData: any[] = [];

export const allCategories = [
  "Best Cancer Specialist Hospital in Varanasi",
  "Best Cardiology Hospital in Varanasi",
  "Best Dental Hospital in Varanasi",
  "Best Eye Specialist Hospital in Varanasi",
  "Best Gynaecologist in Varanasi",
  "Best Heart Hospital in Varanasi",
  "Best Joint Replacement Hospital in Varanasi",
  "Best Medicine Doctor in Varanasi",
  "Best Microbiology Lab in Varanasi",
  "Best Neurology Hospital in Varanasi",
  "Best Orthopedic Hospital in Varanasi",
  "Best Plastic Surgery Hospital in Varanasi",
  "Best Urologist Hospital in Varanasi",
  "Gastroenterology in Varanasi",
  "Cardiology in Varanasi",
  "Neurology in Varanasi",
  "Orthopedics in Varanasi",
  "ENT Care in Varanasi",
  "Pediatrics in Varanasi",
  "Emergency Care in Varanasi",
  "Blood Bank in Varanasi",
  "Critical Care & ICU in Varanasi",
  "Endocrinology Center in Varanasi",
  "Nephrology Specialist Center in Varanasi",
  "Neuro Surgery Center in Varanasi",
  "Laparoscopic Surgeon in Varanasi",
];
