import type { PatientStory } from "./api";

export const fallbackPatientStories: PatientStory[] = [
  {
    _id: "fallback-1",
    title: "Success Story: Cancer Care Journey",
    name: "Patient Story 1",
    videoUrl: "/videos/testimonial-one.mp4",
    thumbnailUrl: "",
    order: 0,
    isActive: true,
  },
  {
    _id: "fallback-2",
    title: "A New Life: Recovery from Critical Condition",
    name: "Patient Story 2",
    videoUrl: "/videos/testimonial-two.mp4",
    thumbnailUrl: "",
    order: 1,
    isActive: true,
  },
  {
    _id: "fallback-3",
    title: "Advanced Medical Care Experience",
    name: "Patient Story 3",
    videoUrl: "/videos/popular_hospital_happy_pateint_one.mp4",
    thumbnailUrl: "",
    order: 2,
    isActive: true,
  },
  {
    _id: "fallback-4",
    title: "Excellence in Specialised Treatment",
    name: "Patient Story 4",
    videoUrl: "/videos/popular_hospital_happy_pateint_two.mp4",
    thumbnailUrl: "",
    order: 3,
    isActive: true,
  },
  {
    _id: "fallback-5",
    title: "Compassionate Care & Fast Recovery",
    name: "Patient Story 5",
    videoUrl: "/videos/popular_hospital_happy_pateint_three.mp4",
    thumbnailUrl: "",
    order: 4,
    isActive: true,
  },
  {
    _id: "fallback-6",
    title: "Advanced Technology for Better Health",
    name: "Patient Story 6",
    videoUrl: "/videos/popular_hospital_happy_pateint_four.mp4",
    thumbnailUrl: "",
    order: 5,
    isActive: true,
  },
  {
    _id: "fallback-7",
    title: "Transforming Lives Through Surgery",
    name: "Patient Story 7",
    videoUrl: "/videos/popular_hospital_happy_pateint_five.mp4",
    thumbnailUrl: "",
    order: 6,
    isActive: true,
  },
];
